# coding: utf-8

"""
    Span

    Span Panel REST API

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import datetime
import unittest

from span_panel.client.models.relay_state import RelayState  # noqa: E501


class TestRelayState(unittest.TestCase):
    """RelayState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRelayState(self):
        """Test RelayState"""
        # inst = RelayState()


if __name__ == "__main__":
    unittest.main()
