#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo ${BASH_SOURCE[0]}
BASE_DIR=$( realpath $( dirname "${BASH_SOURCE[0]}" )/../ )
echo $BASE_DIR
source "$BASE_DIR/.bin/lib/common.sh"
setRoot

PYTEST_EXTRA_ARGS="${PYTEST_EXTRA_ARGS:-}"

pushd "$ROOT_PATH" 2>&1 >/dev/null

rm -rf .coverage*

pytest --timeout=10 --color=yes --cov-report= --maxfail=10 $PYTEST_EXTRA_ARGS

popd 2>&1 >/dev/null
