#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

BASE_DIR=$( realpath $( dirname "${BASH_SOURCE[0]}" )/../ )
source "$BASE_DIR/.bin/lib/common.sh"
setRoot

PYTEST_EXTRA_ARGS="${PYTEST_EXTRA_ARGS:-}"

pushd "$ROOT_PATH" 2>&1 >/dev/null

rm -rf .coverage*

# TODO: add tests
pytest --timeout=10 --color=yes --cov-report= --maxfail=10 $PYTEST_EXTRA_ARGS || true

popd 2>&1 >/dev/null
