name: CD - Release

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      rebuild:
        description: 'Rebuild tag?'
        required: true
        default: 'no'
        type: choice
        options:
        - "no"
        - "yes"

concurrency:
  group: docker-${{ github.event.workflow_run.head_branch || github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: write

env:
  DEFAULT_PYTHON: "3.12"

jobs:
  docs:
    name: Publish Docs
    runs-on: ubuntu-latest

    steps:
    - name: Check repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '${{ env.DEFAULT_PYTHON }}'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade uv
        uv pip install --system -r requirements.txt -r dev-requirements.txt
        uv pip install --system  -e ".[dev]"

    - name: Get current version
      run: echo "PYSPAN_VERSION=$(git describe --tags --abbrev=0 | sed "s/\(v[0-9]\+\.[0-9]\+\.\)[0-9]\+/\1x/")" >> $GITHUB_ENV

    - name: Setup Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    - name: Build and deploy docs
      run: mike deploy --push --update-aliases ${{ env.PYSPAN_VERSION }} latest

  pypi:
    name: Publish to PyPi
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write

    steps:
    - name: Check repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '${{ env.DEFAULT_PYTHON }}'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade uv
        uv pip install --system build

    - name: Build package
      run: python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    environment:
      name: release

    steps:
      - name: Check repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '${{ env.DEFAULT_PYTHON }}'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade uv
          uv pip install --system -r requirements.txt -r dev-requirements.txt
          uv pip install --system -e ".[dev]"

      - name: Get current version (rebuild)
        if: ${{ inputs.rebuild == 'yes' }}
        run: |
          PYSPAN_VERSION=$(git describe --tags --abbrev=0)

          echo "PYSPAN_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo "DOCKER_TAGS=ghcr.io/angellusmortis/span-panel:dev,ghcr.io/angellusmortis/span-panel:$PYSPAN_VERSION" >> $GITHUB_ENV

      - name: Get current version (no rebuild)
        if: ${{ inputs.rebuild != 'yes' }}
        run: |
          PYSPAN_VERSION=v$(python -c 'from importlib.metadata import version; print(version("span-panel"))')

          echo "PYSPAN_VERSION=$PYSPAN_VERSION" >> $GITHUB_ENV
          echo "DOCKER_TAGS=ghcr.io/angellusmortis/span-panel:dev,ghcr.io/angellusmortis/span-panel:$(echo $PYSPAN_VERSION | tr "+" -)" >> $GITHUB_ENV

      - name: Add Latest Docker Tag
        run: |
          if [[ ! "$PYSPAN_VERSION" == *"dev"* ]]; then
            echo "DOCKER_TAGS=ghcr.io/angellusmortis/span-panel:latest,$DOCKER_TAGS" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          target: prod
          push: true
          build-args: |
            PYSPAN_VERSION=${{ env.PYSPAN_VERSION }}
          cache-from: ghcr.io/angellusmortis/span-panel:buildcache
          cache-to: type=registry,ref=ghcr.io/angellusmortis/span-panel:buildcache,mode=max
          tags: ${{ env.DOCKER_TAGS }}
